"""
RiskLens AI — Notification Service
Routes notifications to the appropriate channel based on severity escalation matrix.
"""

from datetime import datetime
from typing import Optional
from app.core.logger import get_logger
from app.core.constants import CHANNEL_EMAIL, CHANNEL_JIRA, CHANNEL_WEBSOCKET, CHANNEL_DASHBOARD
from app.infrastructure.external.email_client import EmailClient, JiraClient
from app.infrastructure.database.repositories.assessment_repo import AlertRepository
from app.infrastructure.websocket.manager import ws_manager

logger = get_logger("services.notification")


class NotificationService:
    """Dispatches notifications to configured channels."""

    async def send_notification(
        self,
        alert: dict,
        assessment: dict,
        channel: str,
        portfolio: dict,
    ) -> bool:
        """Send a notification through the specified channel.

        Args:
            alert: Alert data dict
            assessment: Full assessment data dict
            channel: Notification channel (email, jira, websocket, dashboard)
            portfolio: Portfolio data dict

        Returns:
            True if notification was sent successfully
        """
        try:
            if channel == CHANNEL_EMAIL:
                return await self._send_email(alert, assessment, portfolio)
            elif channel == CHANNEL_JIRA:
                return await self._create_jira_ticket(alert, assessment, portfolio)
            elif channel == CHANNEL_WEBSOCKET:
                return await self._send_websocket(alert)
            elif channel == CHANNEL_DASHBOARD:
                # Dashboard updates happen via WebSocket broadcast in risk_analysis_service
                return True
            else:
                logger.warning(f"Unknown notification channel: {channel}")
                return False
        except Exception as e:
            logger.error(f"Notification failed on channel {channel}", error=str(e))
            return False

    async def _send_email(self, alert: dict, assessment: dict, portfolio: dict) -> bool:
        """Send email notification."""
        manager_email = portfolio.get("manager_email", "risk-desk@example.com")
        subject = f"🚨 {alert['severity']} RISK: {alert['title']}"
        body = EmailClient.build_alert_email_body(alert, assessment)

        success = await EmailClient.send_alert_email(
            to_email=manager_email,
            subject=subject,
            body_html=body,
        )

        # Record notification in alert
        notification_record = {
            "channel": "email",
            "recipient": manager_email,
            "sent_at": datetime.utcnow().isoformat(),
            "status": "delivered" if success else "failed",
        }
        await AlertRepository.update_notifications(alert["_id"], notification_record)

        return success

    async def _create_jira_ticket(self, alert: dict, assessment: dict, portfolio: dict) -> bool:
        """Create Jira ticket."""
        priority_map = {"LOW": "Low", "MEDIUM": "Medium", "HIGH": "High", "CRITICAL": "Highest"}
        priority = priority_map.get(alert["severity"], "Medium")

        claude_analysis = assessment.get("claude_analysis", {})
        rationale = claude_analysis.get("rationale", "No AI rationale available.")
        actions = claude_analysis.get("recommended_actions", [])
        actions_text = "\n".join(f"- {a}" for a in actions)

        description = (
            f"Portfolio: {alert['portfolio_id']}\n"
            f"Severity: {alert['severity']}\n"
            f"Breach: {alert['title']}\n\n"
            f"AI Rationale:\n{rationale}\n\n"
            f"Recommended Actions:\n{actions_text}\n\n"
            f"Assessment ID: {assessment.get('_id', 'N/A')}\n"
            f"Generated by RiskLens AI"
        )

        ticket_key = await JiraClient.create_ticket(
            summary=f"[{alert['severity']}] {alert['title']}",
            description=description,
            priority=priority,
            labels=["risk-alert", "auto-generated", alert["severity"].lower()],
        )

        # Record notification in alert
        notification_record = {
            "channel": "jira",
            "ticket_id": ticket_key or "FAILED",
            "sent_at": datetime.utcnow().isoformat(),
            "status": "created" if ticket_key else "failed",
        }
        await AlertRepository.update_notifications(alert["_id"], notification_record)

        return ticket_key is not None

    async def _send_websocket(self, alert: dict) -> bool:
        """Send WebSocket push notification."""
        await ws_manager.broadcast_alert(alert)
        return True
